# Generated by Django 4.1.1 on 2023-09-22 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='The end time must be later than the start time.', verbose_name='end'),
            preserve_default=False,
        ),
    ]
